/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/full-moon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere037.geometry}
        material={materials['FULL MOON']}
        position={[-0.027, 1.373, 0.002]}
        rotation={[0.943, 1.206, -0.413]}
        scale={1.271}
      />
    </group>
  )
}

useGLTF.preload('/models/full-moon.glb')
