/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to use MeshTransmissionMaterial
*/

import { useGLTF, MeshTransmissionMaterial } from '@react-three/drei'

export function Model(props: any) {
  const { nodes } = useGLTF('/models/planets.glb') as any

  // Material properties for main planet
  const mainPlanet = {
    transmission: 1,
    roughness: 0.2,
    thickness: 1,
    ior: 1.5,
    chromaticAberration: 0.5,
    anisotropy: 0.3,
    distortion: 0.2,
    distortionScale: 0.5,
    temporalDistortion: 0.1,
    color: '#ff9999',
  }

  // Material properties for blue planet
  const bluePlanet = {
    transmission: 1,
    roughness: 0.15,
    thickness: 1.2,
    ior: 1.5,
    chromaticAberration: 0.6,
    anisotropy: 0.3,
    distortion: 0.3,
    distortionScale: 0.5,
    temporalDistortion: 0.1,
    color: '#6699ff',
  }

  // Material properties for yellow planes
  const yellowPlanes = {
    transmission: 1,
    roughness: 0.1,
    thickness: 0.8,
    ior: 1.5,
    chromaticAberration: 0.4,
    anisotropy: 0.3,
    distortion: 0.15,
    distortionScale: 0.4,
    temporalDistortion: 0.1,
    color: '#ffff66',
  }

  // Material properties for ring
  const ring = {
    transmission: 1,
    roughness: 0.25,
    thickness: 1.5,
    ior: 1.5,
    chromaticAberration: 0.3,
    anisotropy: 0.3,
    distortion: 0.1,
    distortionScale: 0.3,
    temporalDistortion: 0.05,
    color: '#ffccff',
  }

  // Global settings
  const global = {
    samples: 16,
    resolution: 512,
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        position={[0, -0.166, 0]}
        rotation={[0.221, 0.142, 0.563]}
        scale={1.035}>
        <MeshTransmissionMaterial
          backside
          samples={global.samples}
          resolution={global.resolution}
          {...mainPlanet}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          position={[-0.171, 1.39, -0.372]}
          rotation={[-0.262, 0, -0.579]}
          scale={1.098}
        >
          <MeshTransmissionMaterial
            backside
            samples={global.samples}
            resolution={global.resolution}
            {...bluePlanet}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          position={[1.547, 0.546, -0.146]}
          rotation={[1.639, -1.126, 0.77]}
          scale={0.788}
        >
          <MeshTransmissionMaterial
            backside
            samples={global.samples}
            resolution={global.resolution}
            {...yellowPlanes}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          position={[0.281, -1.323, 0.355]}
          rotation={[1.198, -1.347, 0.09]}
          scale={0.527}
        >
          <MeshTransmissionMaterial
            backside
            samples={global.samples}
            resolution={global.resolution}
            {...yellowPlanes}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001.geometry}
        >
          <MeshTransmissionMaterial
            backside
            samples={global.samples}
            resolution={global.resolution}
            {...ring}
          />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/planets.glb')
