/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to use MeshTransmissionMaterial with Leva controls
*/

import React, { useRef } from 'react'
import { useGLTF, MeshTransmissionMaterial } from '@react-three/drei'
import { useControls } from 'leva'

export function Model(props) {
  const { nodes } = useGLTF('/models/planets.glb')

  // Leva controls for main planet
  const mainPlanet = useControls('Main Planet (Red)', {
    transmission: { value: 1, min: 0, max: 1, step: 0.01 },
    roughness: { value: 0.2, min: 0, max: 1, step: 0.01 },
    thickness: { value: 1, min: 0, max: 5, step: 0.1 },
    ior: { value: 1.5, min: 1, max: 2.5, step: 0.05 },
    chromaticAberration: { value: 0.5, min: 0, max: 1, step: 0.01 },
    anisotropy: { value: 0.3, min: 0, max: 1, step: 0.01 },
    distortion: { value: 0.2, min: 0, max: 1, step: 0.01 },
    distortionScale: { value: 0.5, min: 0, max: 1, step: 0.01 },
    temporalDistortion: { value: 0.1, min: 0, max: 1, step: 0.01 },
    color: '#ff9999',
  })

  // Leva controls for blue planet
  const bluePlanet = useControls('Blue Planet', {
    transmission: { value: 1, min: 0, max: 1, step: 0.01 },
    roughness: { value: 0.15, min: 0, max: 1, step: 0.01 },
    thickness: { value: 1.2, min: 0, max: 5, step: 0.1 },
    ior: { value: 1.5, min: 1, max: 2.5, step: 0.05 },
    chromaticAberration: { value: 0.6, min: 0, max: 1, step: 0.01 },
    anisotropy: { value: 0.3, min: 0, max: 1, step: 0.01 },
    distortion: { value: 0.3, min: 0, max: 1, step: 0.01 },
    distortionScale: { value: 0.5, min: 0, max: 1, step: 0.01 },
    temporalDistortion: { value: 0.1, min: 0, max: 1, step: 0.01 },
    color: '#6699ff',
  })

  // Leva controls for yellow planes
  const yellowPlanes = useControls('Yellow Planes', {
    transmission: { value: 1, min: 0, max: 1, step: 0.01 },
    roughness: { value: 0.1, min: 0, max: 1, step: 0.01 },
    thickness: { value: 0.8, min: 0, max: 5, step: 0.1 },
    ior: { value: 1.5, min: 1, max: 2.5, step: 0.05 },
    chromaticAberration: { value: 0.4, min: 0, max: 1, step: 0.01 },
    anisotropy: { value: 0.3, min: 0, max: 1, step: 0.01 },
    distortion: { value: 0.15, min: 0, max: 1, step: 0.01 },
    distortionScale: { value: 0.4, min: 0, max: 1, step: 0.01 },
    temporalDistortion: { value: 0.1, min: 0, max: 1, step: 0.01 },
    color: '#ffff66',
  })

  // Leva controls for ring
  const ring = useControls('Ring', {
    transmission: { value: 1, min: 0, max: 1, step: 0.01 },
    roughness: { value: 0.25, min: 0, max: 1, step: 0.01 },
    thickness: { value: 1.5, min: 0, max: 5, step: 0.1 },
    ior: { value: 1.5, min: 1, max: 2.5, step: 0.05 },
    chromaticAberration: { value: 0.3, min: 0, max: 1, step: 0.01 },
    anisotropy: { value: 0.3, min: 0, max: 1, step: 0.01 },
    distortion: { value: 0.1, min: 0, max: 1, step: 0.01 },
    distortionScale: { value: 0.3, min: 0, max: 1, step: 0.01 },
    temporalDistortion: { value: 0.05, min: 0, max: 1, step: 0.01 },
    color: '#ffccff',
  })

  // Global controls
  const global = useControls('Global', {
    samples: { value: 16, min: 1, max: 32, step: 1 },
    resolution: { value: 512, min: 128, max: 2048, step: 128 },
  })

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        position={[0, -0.166, 0]}
        rotation={[0.221, 0.142, 0.563]}
        scale={1.035}>
        <MeshTransmissionMaterial
          backside
          samples={global.samples}
          resolution={global.resolution}
          {...mainPlanet}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          position={[-0.171, 1.39, -0.372]}
          rotation={[-0.262, 0, -0.579]}
          scale={1.098}
        >
          <MeshTransmissionMaterial
            backside
            samples={global.samples}
            resolution={global.resolution}
            {...bluePlanet}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          position={[1.547, 0.546, -0.146]}
          rotation={[1.639, -1.126, 0.77]}
          scale={0.788}
        >
          <MeshTransmissionMaterial
            backside
            samples={global.samples}
            resolution={global.resolution}
            {...yellowPlanes}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          position={[0.281, -1.323, 0.355]}
          rotation={[1.198, -1.347, 0.09]}
          scale={0.527}
        >
          <MeshTransmissionMaterial
            backside
            samples={global.samples}
            resolution={global.resolution}
            {...yellowPlanes}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001.geometry}
        >
          <MeshTransmissionMaterial
            backside
            samples={global.samples}
            resolution={global.resolution}
            {...ring}
          />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/planets.glb')
